### ISSUE TITLE
[FEATURE] 음식 추가, 삭제와 최종 결정

### ISSUE THREAD

**Issue by ywonchae1** [ywonchae1/23-1swad-kiosk#5]
## Issue: ✅ [FEATURE]
버튼을 누를 시 음식 추가, 삭제, 결정
## Description
음식마다 추가 버튼이 있음
추가 버튼을 누르면 장바구니에 내역 표시
장바구니에서 삭제 버튼을 눌러 삭제
## Todo
- [x] 음식마다 추가 버튼 만들기
- [x] 추가된 음식을 장바구니에 표시
- [x] 음식 종류 별로, 개수로 표시 (햄버거 1 | 콜라 3 | 프라이 0)
- [x] 장바구니에서 삭제 버튼을 누르면 삭제
- [x] 장바구니에서 확정 버튼을 누르면 구매 확정(일단 콘솔 출력, 결제로 넘김)

## ETC
[Panel 배치](https://bskwak.tistory.com/181)
[MVC](https://dev4-me.tistory.com/entry/MVC-%ED%8C%A8%ED%84%B4%EC%9D%84-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-Java-SWING%EC%9C%BC%EB%A1%9C-%EA%B3%84%EC%82%B0%EA%B8%B0-%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%A8-%EB%A7%8C%EB%93%A4%EA%B8%B0)
[ActionListener](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=brood1024&logNo=80154309186)
